enter('???', 'no_highlight')
wait(2)

enterNVL()
speak('???', "LLLLLL L LL LLLL LLLLM LM LMLL MLM LML LLLLLLL")
exitNVL()
wait(1)
enterNVL()
speak('???', "LL LLMMAMALML ML ML M L LLLILL MLALI LIM LIM LLLAM LIAM LIAM LIAM LIAM")
exitNVL()
wait(1)
enterNVL()
speak('???', "LIAM.")
exitNVL()
wait(2)
enterNVL()
speak('???', "..........")
exitNVL()
wait(1)

enterNVL()
speak('???', "..........")
choose("Mom, I'm sorry", "......")
speak('???', "...............................................")
choose("How are you?", "......")
speak('???', "...........A Lost And Wrong Friend............ Begin Healer.........................")
speak('???', "....................Shea Toulouse........................................")
speak('???', "...........................Is It?...............")
choose("...Yeah, my back. It hurts...", "......")
speak('???', ".................................................................")
speak('???', "There Was A Bed............ And A Beside........................")
speak('???', "There Was A Sickness........................... And A Machine...............")
speak('???', "There Was A Lie...................... And A Haphazard........................")
speak('???', "There Was A Fight........................ And A Corral........................")
speak('???', "There Was A Death........................ And Its Opposite........................")
speak('???', "There Was A Boy................................And His Cure................................................")
exitNVL()
choose("Feat to Recollect", "...I can't remember.")

wait(2)

enterNVL()
speak('???', "..........................................................")
speak('???', "...........He Remembers.........Thought He Once Had.................")
speak('???', "........................No Gas Left In The Tank........................")
exitNVL()
choose("I... I can't... Trying...", "I just... let it happen.")

wait(2)
speak('???', ".............Nothing Left To Give...................")
speak('???', ".....................Right There.................... From The First Ringing Of The Bell.........")
speak('???', "...................................")
speak('???', "......A Phone Call.....................")
choose("Mom, I'm sorry.", "Do You Remember Me?")
speak('???', ".....................................................")
speak('???', ".............The Boy Heard The News........................................")
speak('???', "........................And Saw.............Crows Fly..................................")
speak('???', "........................He Held That As Potential...........................")
speak('???', "No Sight....................................... No Mind")
speak('???', ".............No Way To Know..........Where You Went")
choose("I Just Want To See You Again", ".....It Can’t End.......")
speak('???', "........................")
speak('???', "........................No Need To Break A Circle....................................")
speak('???', "..............It Was Too Shallow.........")
speak('???', "..................Too Fallowed, Reaped, Deep And Gone..................")
speak('???', ".........................................................................")
speak('???', ".........................................................................")
speak('???', ".........................................................................")
speak('???', "The Crows Are Circling Around and Around")
speak('???', "The Crows Are Circling Around and Around")
speak('???', "The Crows Are Circling Around and Around")
speak('???', "The Crows Are Circling Around and Around")
speak('???', "..................")
exitNVL()

wait(2)

enterNVL()
speak('???', "Find Me Over And Over Again")
exitNVL()
exit('???')

wait(3)
mom(false)
video(.4)
teleport('Finale', 'true')