--play sfx

setSwitch('gps_error', true)
playSFX('gps_recalc')
wait(1.5)
setSwitch('gps_error', false)
wait(1.5)

enterNVL()
speak('ALISTAIR', "You miss a turn there, Liam?")
speak('LIAM', "I know where I'm going.")
speak('BIANCA', "Maybe the GPS lost signal?")
speak('LIAM', "Maybe disconnect and reconnect it.")
speak('BIANCA', "Yeah, I’ll try that. Good call.")
exitNVL()

wait(0.5)
setSwitch('gps_on', false)
wait(2.0)
setSwitch('gps_on', true)
setSwitch('gps_error', true)
wait(3.0)
setSwitch('gps_error', false)
playSFX('gps_continue_70')

driveWait(15)

enterNVL()
speak('CYN', "Oh, look at this dream team working together. They’re so cute!")
speak('ALISTAIR', "How’d you two meet anyway?")
speak('CYN', "Ooooooh, this is a good one!")
speak('BIANCA', "Liam, would you like to tell the story?")
speak('LIAM', "I'm not very good at it.")
speak('CYN', "Oh, come on! I’ve heard it many times from Bee herself. Would be nice to hear it from the other side!")
speak('ALISTAIR', "Yeah Liam. Spill.")
speak('LIAM', "Okay.")
if choose("It was a networking event", "We met at a coffee shop") then
	speak('CYN', "Ooh, networking! That’s a fun way to put it.")
	speak('BIANCA', "That is ...fun... isn't it?")
	speak('CYN', "I’d call it a party at a dive bar, more like!")
	speak('ALISTAIR', "That sounds more Liam's style.")
	speak('LIAM', "It was for a work thing, it was just... networking. That’s what it was, technically.")
	speak('CYN', "Everything’s networking. You fancied a waitress.")
	speak('BIANCA', "Yeah, he gave me the biggest tip ever.")
	speak('ALISTAIR', "And then he invited you out while you were on the job?")
	speak('BIANCA', "How’d you know?")
	speak('LIAM', "I'm not very glamorous.")
	speak('BIANCA', "And then he waited. For a long time. It wasn’t until later on when he followed up.")
else
	speak('CYN', "And who was working as the barista?")
	speak('LIAM', "I was.")
	speak('CYN', "I bet you make a mean espresso.")
	speak('ALISTAIR', "He makes coffee? I wouldn’t bet it’s very high quality.")
	speak('BIANCA', "He’s... okay at it. But he brought much more than that, just... a lot later on.")
end

speak('CYN', "A lot later on. You didn’t even kiss until the.. seventh date, wasn’t it?")
speak('BIANCA', "Did I honestly tell you that?")
speak('CYN', "I remember everything, Bee. My mind is a steel trap.")
speak('ALISTAIR', "Seven dates! That's a long time...")

setSwitch('gps_error', true)
playSFX('gps_recalc')
choose("It's not very long!", "I guess it's long...")

speak('ALISTAIR', "You were much quicker with all those other girls you’ve kissed. Technically first date on all of them!")
speak('ALISTAIR', "What happened?")
speak('CYN', "I’m sure people grow up and become different as they get older?")
speak('BIANCA', "I don’t really want to think about that.")
speak('ALISTAIR', "My bad. It’s just that he’s usually well-known for being quick to go!")

if choose("That's none of your business, really.", "What, are you envious?") then
	speak('ALISTAIR', "Oh, isn’t it? Funny how that all fades away once you live a comfy life in The Big Apple.")
	exitNVL()
	driveWait(15)
	setSwitch('gps_error', false)
	playSFX('gps_continue_3000')
	driveWait(15)
	enterNVL()
	speak('CYN', "That’s New York City, Alistair. Not DC.")
	speak('ALISTAIR', "Oh. Right. The Big Pear, then.")
	speak('LIAM', "The Big Pear... How cool. Like the Big Apple, but a pear instead.")
	speak('ALISTAIR', "Hey. If you don’t like my classic comedy genius, keep driving and quit yapping.")
	speak('ALISTAIR', "Just stay in your lane, friend.")
	speak('LIAM', "It’s weird when you say \"friend\" like that.")
else
	speak('LIAM', "You can talk. Half the amount of girls I’ve kissed... you wouldn’t even meet that margin.")
	speak('ALISTAIR', "Not a competition!")
	exitNVL()
	driveWait(8)
	setSwitch('gps_error', false)
	playSFX('gps_continue_3000')
	driveWait(8)
	enterNVL()
	speak('ALISTAIR', "Especially bragging while you’re tied down. Quite a dangerous pursuit, my friend!")
	speak('LIAM', "Don't say \"friend\" like that.")
end

speak('ALISTAIR', "Everyone’s my friend. You’re not special.")
speak('CYN', "I'm glad to be your friend.")
speak('ALISTAIR', "Especially you, Cyn. You deserve it the most of all!")
speak('BIANCA', "Okay. She’s my friend.")
speak('CYN', "Yeah! Bee’s my ride or die. She's my number one friend, sad to say.")
speak('ALISTAIR', "Need a challenge for that spot?")
speak('BIANCA', "No. She’s fine with me.")
speak('ALISTAIR', "No. Good! Wasn’t gonna.")
speak('CYN', "You’re very forward.")
speak('ALISTAIR', "I’ve learned to be that way. Everyone dismisses you unless you’re confident.")
speak('ALISTAIR', "Otherwise they just step on you, and that’s your legacy.")
exitNVL()
driveWait(45)
enterNVL()
speak('CYN', "Right. I think I get what you mean.")
exitNVL()

driveWait(300)

fadeOutBGM(3)
fade('black', 4)
teleport('Nighttime_PurpleMist', true)