playBGM('finale')

choose("....", "....")
enter('BIANCA')
enterNVL()
speak('BIANCA', "Liam.")
choose("....", "....")
speak('BIANCA', "Can you see the road ahead?")
choose("........", "........Yes.")
speak('BIANCA', "Hey. Liam. I love you.")
speak('BIANCA', "Thanks for taking us on this trip.")
choose("(I mourn my hope.)", "(I mourn my muse.)")
speak('BIANCA', ".............You Find What You Search For.............")
choose("(I remember my connection.)", "(I forgive my community.)")
exitNVL()

setSpeed(30)
driveWait(60)

enter('ALISTAIR')
enterNVL()
speak('ALISTAIR', "Steady on there, lad.")
exitNVL()
enter('CYN')
enterNVL()
speak('CYN', "It’s going to be okay, Alistair. He’s our driver. He has full control.")
speak('BIANCA', "............The Crows Delight In Their Circles............")
speak('BIANCA', "............Around And Around They Spin........................")
exitNVL()
choose("(I keep my love.)", "(I keep my pain.)")

setSpeed(33)
driveWait(60)

speak('CYN', "We trust you, Liam.")
speak('BIANCA', "............Over And Over The Rotations Devolve........................")
speak('CYN', "Thank you for being our driver.")
choose("(I forgive my mother.)", "(I forgive  my friend.)")
speak('ALISTAIR', "It’s okay, Liam. You did what you could in order to survive.")
speak('ALISTAIR', "I’m thankful that you invited me. It was the best thing that could have happened to me.")
choose("(I keep myself.)", "(I keep myself.)")
speak('BIANCA', "The Crows Circle Unto Themselves")
exitNVL()

setSpeed(35)
driveWait(70)
setSwitch('snap_cam', true)
wait(.5)
setSwitch('snap_cam', false)

driveWait(60)
enterNVL()
speak('ALISTAIR', "It’s okay, Cyn.")
speak('CYN', "...")
speak('ALISTAIR', "Let go.")
exitNVL()

driveWait(70)
setSwitch('snap_cam', true)
wait(.4)
setSwitch('snap_cam', false)
wait(.4)
setSwitch('snap_cam', true)
wait(.4)
setSwitch('snap_cam', false)
wait(.4)
setSwitch('snap_cam', true)
wait(.4)
setSwitch('snap_cam', false)
wait(.4)

setSpeed(38)
driveWait(100)

enterNVL()
speak('BIANCA', "Find Me Over And Over Again")
exitNVL()

play('scene7_05')