impact()
wait(3.5)

enterNVL()
speak('BIANCA', "Liam! Are you okay?")
speak('ALISTAIR', "What in the world was THAT?")
speak('BIANCA', "I think we've hit... something.")
speak('CYN', "No! Poor thing. I don't want to see any carnage!")
speak('ALISTAIR', "We have to check the car for damage. Come on guys.")
exitNVL()

exit('ALISTAIR')
wait(.8)
exit('BIANCA')
wait(1.5)
exit('CYN')
wait(.5)
setSwitch('alistar_scene6', true)
wait(.8)
setSwitch('cyn_scene6', true)