enterNVL()
speak('LIAM', "I bet it's good work. Filleting fish.")
speak('ALISTAIR', "It's not. Makes we want to kill myself.")
exitNVL()

driveWait(30)

setSwitch('needs_gas', true)

driveWait(60)

speak('ALISTAIR', "Fine. How about you? What have you been up to in the Big City?")
speak('LIAM', "I'm an accountant.")
speak('ALISTAIR', "No fun! I was supposed to guess!")
speak('ALISTAIR', "So is that why you left Fuseville? To count someone else’s money?")
speak('LIAM', "Better than staying in a filthy old town.")
speak('ALISTAIR', "Ah, right. Everyone being shit and all, I remember that.")
speak('LIAM', "Yeah. No hopes, no dreams. Just staying in your little lives with no ambitions.")
speak('BIANCA', "Liam, that's enough.")
speak('ALISTAIR', "I guess that’s one way to remember it.")
speak('LIAM', "Can’t think of another fair way to remember a shithole.")
speak('BIANCA', "Enough. Please.")
speak('ALISTAIR', "You could remember it as community. Love. Something other than stone cold self-reliance and isolation.")
speak('LIAM', "Some things are better left alone.")
speak('ALISTAIR', "Oh yeah, you’d know about leaving things alone, wouldn’t you?")
speak('LIAM', "Okay. That’s enough of that.")
speak('ALISTAIR', "Enough when it’s convenient. Hit a sore spot, have I?")
speak('BIANCA', "Guys, this is quite full-on. Please stop.")
speak('LIAM', "That didn’t happen.")
speak('ALISTAIR', "Oh yeah it did. You want me to dredge up old things?")
speak('BIANCA', "That’s enough, Alistair.")
speak('ALISTAIR', "You come to his rescue, then. That’s fine.")
choose("Be quiet, now.", "Tighten flapping lips.")
speak('ALISTAIR', "You get ugly when you’re angry.")
speak('LIAM', "I’d shut up if I were you right now.")
speak('ALISTAIR', "And why should I? After what you did to your mother?")
exitNVL()
choose("........", "........")

play('scene6_03')