setSpeed(35)

driveWait(200)

enterNVL()
speak('BIANCA', "...gross, whatever it was...")
exitNVL()
wait(.5)
enterNVL()
speak('ALISTAIR', "...too big for a raccoon...")
exitNVL()
wait(.5)
enterNVL()
speak('CYN', "...moved too fast, with legs like that, something different...")
exitNVL()
wait(.5)
enterNVL()
speak('ALISTAIR', "...no, would've damaged the car if it were a deer...")
exitNVL()

driveWait(100)

choose("........", "........")
enterNVL()
speak('BIANCA', "Hang on, Liam. You’re bleeding.")
speak('ALISTAIR', "Where?")
speak('BIANCA', "Are you alright?")
choose("........", "........")
speak('BIANCA', "You okay?")
speak('CYN', "Oh, it’s all over the seat. Does someone have a cloth?")
speak('BIANCA', "Where did all that come from?")
speak('ALISTAIR', "Gross.")
speak('BIANCA', "Liam are you okay?")
exitNVL()

setSpeed(20)
wait(.3)

enterNVL()
speak('BIANCA', "Huh?")
speak('BIANCA', "Liam, you need to tell me what’s going on.")
choose("...", ".............")
choose(".............", "...") 
choose("........", "........")
speak('BIANCA', "Come on, Liam. Come on. Please.")
speak('ALISTAIR', "He's checked out.")
exitNVL()

setSpeed(25)
driveWait(100)

enterNVL()
speak('ALISTAIR', "He used to do that. All the time. He’d check out, and then you couldn’t get him back.")
speak('BIANCA', "Oh no, you’ve got a bit more blood there. On your neck. Let me get it.")
speak('ALISTAIR', "It’s a mechanism. He uses it as a weapon. It’s easy to just ignore.")
speak('BIANCA', "Come on, babe. You’re scaring me.")
choose("........", "........")
speak('BIANCA', "Look, I know hitting something has shaken you. But if you’re not having a good time, you need to stop driving.")
speak('CYN', "He couldn’t be having a stroke, could he?")
speak('ALISTAIR', "He’s not having a stroke.")
speak('CYN', "But if he’s not talking... he went silent all of a sudden, and... I don’t know, how do you detect that? If he’s simply tired or not?")
speak('ALISTAIR', "I tell you, he used to do this all the time.")
exitNVL()
choose("..", ".")

setSpeed(25)
driveWait(60)

enterNVL()
speak('BIANCA', "Liam. Say something. Anything.")
speak('ALISTAIR', "He can.")
speak('BIANCA', "Can you hear me? Raise your left hand. Just a little.")
speak('CYN', "Oh no. This is really bad.")
speak('CYN', "Or do you think he’s angry?")
exitNVL()
choose("..............", "...")

setSpeed(25)
driveWait(60)

enterNVL()
speak('ALISTAIR', "He’s pissed at me. He just doesn’t want to talk. He gets like this.")
speak('ALISTAIR', "Heck, I’ll prove it.")
exitNVL()

wait(1)

enterNVL()
speak('ALISTAIR', "You didn’t want me to come, did you? You invited me because you thought I wouldn’t want to come.")
speak('CYN', "Alistair!")
speak('ALISTAIR', "Let me confront my friend!")
speak('ALISTAIR', "Answer me, Liam! Did you want me to come along to this trip or not?")
choose("................", "................")
speak('ALISTAIR', "I’m assuming that means no. And I think I know why.")
exitNVL()

wait(1)

play('scene7_02')

