enterNVL()
speak('BIANCA', "Cyn! So good to see you!")
speak('CYN', "Bee! How are you, Bee?")
speak('BIANCA', "So good right now! This is gonna be so fun!")
speak('CYN', "I'm excited, too! And you're looking amazing. Look at yourself!")
speak('BIANCA', "Thank you! You’re looking awesome too! All prepped and ready to go!")
speak('BIANCA', "Where'd you get that coat from? It's so nice!")
speak('CYN', "Thank you! I got it from one of the vintage shops, last Friday. It was 20% off, so I figured I just had to.")
speak('BIANCA', "Oh, Cyn, I haven’t been clothes shopping in so long. We need to go! The sooner the better.")
speak('CYN', "Absolutely! It's my fault, honesetly. I'll own it - I haven't contacted you about it.")
speak('BIANCA', "Stop it!")
speak('CYN', "Nooooo, I’ve been lazy about that kinda stuff lately. It's on me, Bee.")
speak('BIANCA', "No, it's on me! I've just been... busy. So busy.")
speak('CYN', "We've both been busy.")
speak('BIANCA', "Yeah. We have!")
exitNVL()
wait(0.5)
enterNVL()
speak('BIANCA', "Want me to pop the trunk?")
speak('BIANCA', "Wait, where's the rest of your stuff?")
speak('CYN', "Oh, no! I’ve got everything. Yup. Right with me.")
speak('BIANCA', "You have?")
speak('CYN', "Yeah, it’s all in here. This little baggie. Gotta travel light!")
speak('BIANCA', "Are you sure you don’t need some, like- towels or something? Or a yoga mat? You know, to yoga with?")
speak('CYN', "Bianca! This isn't a wellness retreat, right?")
speak('BIANCA', "Cyn, it is a wellness retreat! You’re gonna want all the stuff- for the exercises, for the massages- all that stuff!")
speak('LIAM', "I thought this was nature retreat? Like, a cabin-in-the-woods type deal? Hiking through forest?")
speak('BIANCA', "I don't know what you're talking about. That's definitely not what we're doing.")
speak('CYN', "You know- I'm game for anything. As long as I get to meet new people, and have new experiences. That's what's fun for me.")
speak('CYN', "And if there’s a spa, too, well then that’s just extra, isn’t it?")
speak('BIANCA', "And there's yoga sessions, and there's gonna be drinks - mildly alcoholic drinks. And a warm sauna, too! For exhausting all the pores! That's what's fun for me. Add all that stuff together.")
speak('CYN', "Yes! Exciting! Love that for us!")
exitNVL()

allowDriving(true)
wait(3)

enterNVL()
speak('BIANCA', "Oh! I forgot to introduce you two! As you know, or- as you may have heard (via stories and the such like), this is my boyfriend, Liam. Liam - this is Cyn. Cyn, Liam- ")
speak('BIANCA', "Gah, who am I kidding... You both know each other already by proxy! I'm just being the conduit, et cetera...")
speak('CYN', "Oh, I've heard the stories, sure!")

if choose("Hopefully only good ones?", "And I've heard stories about you, Cyn!") then
	speak('CYN', "Sure. And maybe some of the cheekier ones, maybe.")
	speak('CYN', "Not too raw, of course! Just… you know, the fun ones! That's right, Bianca, isn't it?")
else
	speak('CYN', "Hopefully only the good ones!")
end

if getSwitch("wantsMassage") then
	speak('BIANCA', "I need to tell you about the story where he begged me for a massage earlier today.")
	speak('CYN', "Ooh! Another naughty story. I love those!")
	speak('BIANCA', "Tell me about it!")
else
	speak('BIANCA', "I need to tell you about the story where he begged me not to massage him earlier today.")
	speak('CYN', "Ha! Who wouldn't want a massage? Nobody sane, that is.")
	speak('BIANCA', "Tell me about it.")
end
exitNVL()

fadeOutBGM(3)
playBGM('none')

fade('black')
teleport('Residential2', true)