enter('BIANCA')
enterNVL()
speak('BIANCA', "Hi my name is Bianca.")
speak('BIANCA', "I'm in the passenger seat.")
enter('CYN')
speak('CYN', "I'm Cyn. I'm going to talk a lot to stress the textbox wrapping and try to demonstrate how much is reasonable to fit in one line of dialog. Probably you could squeeze three whole lines in here. Impressive, right?")
enter('ALISTAIR')
speak('ALISTAIR', "Alistair here! All I'm here to do is leave.")
speak('LIAM', "Seriously? That's it?")
exit('ALISTAIR')
speak('LIAM', "Oh, you can't see me, but I'm the protagonist.")
speak('LIAM', "Let's cut to black.")
exitNVL()
fade('black', 3.0)
wait(1.0)
fade('white', 1.0)
enterNVL()
speak('LIAM', "Surprise! Still here!")
speak('LIAM', "Okay let's get back to the road, kids.")
exitNVL()